import sys

output	= 'player'

sources = [
            'main.cc',
          ]

env = Environment()

if sys.platform == 'darwin':
	env.Append(CCFLAGS=['-D__MACOSX__','-D__INTERPRETER__'])

	env.Append(CPPPATH=['../BaseLibrary/'])

	env.Append(LIBPATH=['../BaseLibrary/'])
	env.Append(LIBS=['vasik'])

	env.Append(LINKFLAGS='-framework Cocoa')
	
	AddPreAction(sources, "export MACOSX_DEPLOYMENT_TARGET='10.4'")
elif sys.platform == 'linux2':
	env.Append(CCFLAGS=['-D__LINUX__','-D__INTERPRETER__'])

	env.Append(CPPPATH=['../BaseLibrary/'])

	env.Append(LIBPATH=['../BaseLibrary/'])
	env.Append(LIBS=['vasik'])
	
	env.Append(LINKFLAGS='-Wl,-rpath,./')

tgt = env.Program(output, env.Object(sources))
