import sys

output = 'libvasik'

sources = [ 
            'TVasik.cc',
            'TLog.cc',
            'TPlugin.cc',
          ]

env = Environment()          

if sys.platform == 'darwin':
    env.Append(LIBS=['lua'])

    env.Append(CPPFLAGS=['-fno-common'])
    env.Replace(SHLINKFLAGS='-dynamiclib -undefined dynamic_lookup')

    env.Replace(SHLIBPREFIX='')
    env.Replace(SHLIBSUFFIX='.dylib')

objs = env.SharedObject(sources)

env.SharedLibrary(output,objs)
